#!/usr/bin/env python3
"""Build the handbook as one ordered Markdown file."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

FRONT_MATTER = [
    ROOT / "manuscript/00-front-matter/title.md",
    ROOT / "manuscript/00-front-matter/preface.md",
    ROOT / "manuscript/00-front-matter/how-to-use-this-book.md",
    ROOT / "manuscript/00-front-matter/table-of-contents.md",
]

PART_DIRECTORIES = [
    ROOT / "manuscript/part-01-fundamentals",
    ROOT / "manuscript/part-02-modelling-languages",
    ROOT / "manuscript/part-03-diagram-selection",
    ROOT / "manuscript/part-04-architecture-lifecycle",
    ROOT / "manuscript/part-05-bian-case-study",
    ROOT / "manuscript/part-06-practical-reference",
]

APPENDICES = ROOT / "manuscript/appendices"
PAGE_BREAK = "\n\n<div style=\"page-break-after: always;\"></div>\n\n"


def ordered_manuscript_files() -> list[Path]:
    files = list(FRONT_MATTER)
    for directory in PART_DIRECTORIES:
        files.extend(sorted(directory.glob("*.md")))
    files.extend(sorted(APPENDICES.glob("*.md")))
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-directory",
        default="build",
        help="Repository-relative or absolute output directory (default: build)",
    )
    args = parser.parse_args()

    output_directory = Path(args.output_directory)
    if not output_directory.is_absolute():
        output_directory = ROOT / output_directory
    output_directory.mkdir(parents=True, exist_ok=True)

    output_file = output_directory / "architecture-modelling-handbook.md"
    files = ordered_manuscript_files()
    missing = [path for path in files if not path.is_file()]
    if missing:
        print("Cannot build because these files are missing:")
        for path in missing:
            print(f"- {path.relative_to(ROOT)}")
        return 1

    with output_file.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(
            "<!-- Generated by scripts/build-book.py. "
            "Do not edit this file directly. -->\n\n"
        )
        for index, path in enumerate(files):
            handle.write(path.read_text(encoding="utf-8").rstrip())
            if index < len(files) - 1:
                handle.write(PAGE_BREAK)
            else:
                handle.write("\n")

    print(f"Combined Markdown created: {output_file}")
    print(f"Included {len(files)} manuscript files in explicit book order.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
